name: Deploy
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
#  golangci:
#    name: Run linter
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: golangci-lint
#        uses: golangci/golangci-lint-action@v2
#        with:
#          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
#          version: latest

  test:
    name: Run tests
#    needs: [ golangci ]
#    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test -v ./...

  deploy:
    name: Deploy app
    needs: [ test ]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only